### ISSUE TITLE
Comparison with Pinterest Plank

### ISSUE THREAD

**Issue by brurend** [facebook/remodel#82]
What's the main difference and pros/cons between Remodel and Plank? Have you guys done any testing or comparison?

Both seems quite similar and have the same goal, generate immutable models.

**Comment by calimarkus** [comment]
Interesting. I haven't used it (or even heard of it) so far. So this is a very limited opinion. But here are some differences I spotted:

- One difference is the language it is implemented in: Remodel is written in typescript/javascript, whereas Plank is written in Swift.
- Plank seems to generate JSON parsing and model merging code by default. Remodel doesn't out of the box, but the former can easily be achieved by adding a plugin.
- (At a first glance) Plank doesn't seem as extensible/customizable through plugins and configurations. Remodel gives you flexibility & full control, since you can tweak all generated output (and add additional generated classes/methods/properties etc.) by writing custom plugins (in .ts or .js).

That said - I'm not aware of any existing comparisons or measurements.

**Comment by brurend** [comment]
I never used Remodel, but from what you said in your reply those seem to be the main differences indeed.

I shall give a try to Remodel sometime so I can have a better overview about both.

Thank you for taking your time to answer.
